#!/bin/sh
# Install ~/.local/bin/{permissions,spi} pointing at this repo's launcher.
# Run automatically by `npm install` via postinstall.
set -eu

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CLI="$ROOT/permissions/cli/dist/cli.js"
BIN_DIR="${HOME}/.local/bin"
mkdir -p "$BIN_DIR"

ln -sfn "$CLI" "$BIN_DIR/permissions"

cat > "$BIN_DIR/spi" <<EOF
#!/bin/sh
# Auto-generated by permissions postinstall. Runs pi inside the permissions
# sandbox: Seatbelt + MITM proxy + permission gating extension.
exec "$CLI" pi "\$@"
EOF
chmod +x "$BIN_DIR/spi"

echo "linked: $BIN_DIR/permissions -> $CLI"
echo "wrote:  $BIN_DIR/spi (runs: permissions pi \"\$@\")"
